# docker-compose.yml

version: '3'
services:
  db:
    image: postgres:12
    ports:
      - "6543:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
